name = "entrip-uptime-monitor"
main = "uptime.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/5 * * * *"]  # Every 5 minutes

[vars]
ENVIRONMENT = "production"

# Secrets to be set via wrangler secret put
# SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/..."
# WEBHOOK_URL = "https://your-monitoring-endpoint.com/metrics"