server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: tag
            time: time
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          tag:
      - regex:
          expression: ^/var/lib/docker/containers/(?P<container_id>[^/]+)/(?P<log_file>[^/]+)$
          source: filename
      - labels:
          container_id:
      - match:
          selector: '{job="containerlogs"}'
          stages:
            - docker:
            - labels:
                container_name:
                container_image:

  # Flight API specific logs
  - job_name: flight-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: flight-api
          service: entrip-api
          __path__: /var/log/entrip-api/*.log
    
    pipeline_stages:
      - regex:
          expression: '^\[(?P<timestamp>[\d\-\s\:\.]+)\]\s+(?P<level>\w+)\s+(?P<message>.+)$'
      - timestamp:
          format: '2006-01-02 15:04:05.000'
          source: timestamp
      - labels:
          level:
      - match:
          selector: '{job="flight-api"}'
          stages:
            - regex:
                expression: 'TraceID:\s*(?P<trace_id>[a-f0-9]+)'
            - labels:
                trace_id:
            - output:
                source: message