version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: entrip-postgres
    environment:
      POSTGRES_USER: entrip
      POSTGRES_PASSWORD: entrip
      POSTGRES_DB: entrip
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U entrip"]
      interval: 10s
      timeout: 5s
      retries: 5
