apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceName: Tempo
          matcherRegex: "(?:TraceID|trace_id|traceID):\\s*([a-f0-9]+)"
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"
    isDefault: false
    editable: true