// This file is auto-generated by openapi-typescript
// Mock types until real API is available

export interface paths {
  "/api/v1/reservations": {
    get: {
      parameters?: {
        query?: {
          month?: string; // YYYY-MM format
        };
      };
      responses: {
        200: {
          content: {
            "application/json": Reservation[];
          };
        };
      };
    };
  };
  "/api/v1/health": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              status: string;
              timestamp: string;
              uptime: number;
              version: string;
            };
          };
        };
      };
    };
  };
  "/api/v1/bookings": {
    get: {
      parameters?: {
        query?: {
          page?: number;
          limit?: number;
          status?: "pending" | "confirmed" | "cancelled";
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              data: Booking[];
              total: number;
              page: number;
              limit: number;
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": NewBooking;
        };
      };
      responses: {
        201: {
          content: {
            "application/json": Booking;
          };
        };
      };
    };
  };
  "/api/v1/bookings/{id}": {
    get: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": Booking;
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          id: string;
        };
      };
      requestBody: {
        content: {
          "application/json": Partial<Booking>;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": Booking;
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          id: string;
        };
      };
      responses: {
        204: never;
      };
    };
  };
}

export interface Booking {
  id: string;
  teamName: string;
  customerName: string;
  customerPhone: string;
  customerEmail?: string;
  travelDate: string;
  returnDate: string;
  destination: string;
  adultCount: number;
  childCount: number;
  totalAmount: number;
  depositAmount: number;
  status: "pending" | "confirmed" | "cancelled";
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface NewBooking {
  teamName: string;
  customerName: string;
  customerPhone: string;
  customerEmail?: string;
  travelDate: string;
  returnDate: string;
  destination: string;
  adultCount: number;
  childCount: number;
  totalAmount: number;
  depositAmount: number;
  notes?: string;
}

export interface ApiError {
  message: string;
  code?: string;
  details?: unknown;
}

export interface Reservation {
  id: string;
  teamName: string;
  code: string;
  date: string;           // YYYY-MM-DD
  type: string;           // IN, GF, AT...
  status: '확정' | '대기' | '취소';
  people: number;
  amount: number;
  profit?: number;
  manager: string;
}