#!/usr/bin/env bash
set -euo pipefail

# Simple MCP ~/.codex/config.toml generator/merger
# Usage:
#   bash scripts/setup-mcp-config.sh --provider brightData --api-token bd_XXXX --yes
#   bash scripts/setup-mcp-config.sh --provider playwright --yes

PROVIDERS=()
API_TOKEN=""
ASSUME_YES=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --provider)
      PROVIDERS+=("$2"); shift 2 ;;
    --api-token)
      API_TOKEN="$2"; shift 2 ;;
    --yes|-y)
      ASSUME_YES=true; shift ;;
    *)
      echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

CODEx_DIR="${HOME}/.codex"
CONF_FILE="${CODEx_DIR}/config.toml"

mkdir -p "${CODEx_DIR}"

if [[ -f "${CONF_FILE}" ]]; then
  cp -f "${CONF_FILE}" "${CONF_FILE}.bak"
  echo "[info] 기존 설정 백업: ${CONF_FILE}.bak"
fi

# Start with existing or fresh
TMP_FILE=$(mktemp)
if [[ -f "${CONF_FILE}" ]]; then
  cat "${CONF_FILE}" > "${TMP_FILE}"
else
  echo "# Generated by setup-mcp-config.sh" > "${TMP_FILE}"
fi

add_brightdata() {
  if ! grep -q "\[mcp_servers.brightData\]" "${TMP_FILE}"; then
    cat >>"${TMP_FILE}" <<'TOML'

[mcp_servers.brightData]
command = "npx"
args    = ["-y", "@brightdata/mcp"]
env     = { API_TOKEN = "bd_your_api_key_here" }
TOML
  fi
  if [[ -n "${API_TOKEN}" ]]; then
    # Replace placeholder token
    sed -i.bak "s/bd_your_api_key_here/${API_TOKEN}/g" "${TMP_FILE}" || true
  fi
}

add_playwright() {
  if ! grep -q "\[mcp_servers.playwright\]" "${TMP_FILE}"; then
    cat >>"${TMP_FILE}" <<'TOML'

[mcp_servers.playwright]
command = "npx"
args    = ["@playwright/mcp@latest"]
TOML
  fi
}

if [[ ${#PROVIDERS[@]} -eq 0 ]]; then
  echo "[warn] --provider 가 지정되지 않아 기본 제공자(brightData, playwright)를 모두 추가합니다."
  PROVIDERS=(brightData playwright)
fi

for p in "${PROVIDERS[@]}"; do
  case "$p" in
    brightData) add_brightdata ;;
    playwright) add_playwright ;;
    *) echo "[warn] 알 수 없는 provider: $p (무시)" ;;
  esac
done

echo
echo "==== 적용될 설정 미리보기 (~/.codex/config.toml) ===="
cat "${TMP_FILE}"
echo

if [[ "${ASSUME_YES}" = true ]]; then
  ANSWER="y"
else
  read -r -p "위 설정을 저장할까요? [y/N] " ANSWER || true
fi

if [[ "${ANSWER}" =~ ^[Yy]$ ]]; then
  mv -f "${TMP_FILE}" "${CONF_FILE}"
  echo "[ok] 저장 완료: ${CONF_FILE}"
else
  echo "[skip] 저장 취소. 미리보기만 출력했습니다."
  rm -f "${TMP_FILE}"
fi

