name: API CI
on:
  push:
    paths:
      - 'packages/api/**'
      - '.github/workflows/api-ci.yml'
  pull_request:
    paths:
      - 'packages/api/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Build API
        run: pnpm --filter @entrip/api build
      - name: Test API with coverage
        run: pnpm --filter @entrip/api test:coverage
      - name: Upload coverage reports
        uses: codecov/codecov-action@v4
        with:
          flags: api
          directory: ./packages/api/coverage
          token: ${{ secrets.CODECOV_TOKEN }}