name: Route Implementation Check
on:
  pull_request:
    paths:
      - 'apps/web/app/**'
      - 'apps/web/src/**'
      - 'scripts/quick-test.sh'

jobs:
  check-routes:
    name: Check Route Implementation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check for implemented routes still in whitelist
        run: |
          # Extract whitelist from quick-test.sh
          WHITELIST=$(grep -A 10 "EXPECTED_404=(" scripts/quick-test.sh | grep -E '^\s*"/' | tr -d ' "')
          
          # Check if each whitelisted route actually exists
          FOUND_IMPLEMENTED=()
          for route in $WHITELIST; do
            # Remove leading slash and convert to file path
            FILE_PATH=$(echo $route | sed 's|^/||' | sed 's|/$||')
            
            # Check if page.tsx exists
            if [ -f "apps/web/app/${FILE_PATH}/page.tsx" ] || [ -f "apps/web/app/(main)/${FILE_PATH}/page.tsx" ]; then
              FOUND_IMPLEMENTED+=("$route")
            fi
          done
          
          # Report if any implemented routes are still whitelisted
          if [ ${#FOUND_IMPLEMENTED[@]} -gt 0 ]; then
            echo "❌ Found implemented routes still in whitelist:"
            printf '%s\n' "${FOUND_IMPLEMENTED[@]}"
            echo ""
            echo "Please remove these from EXPECTED_404 in scripts/quick-test.sh"
            exit 1
          else
            echo "✅ All whitelisted routes are genuinely not implemented"
          fi