name: Flight API Smoke Test

on:
  schedule:
    # 매일 06:00, 12:00, 18:00 KST (21:00, 03:00, 09:00 UTC)
    - cron: '0 21 * * *'
    - cron: '0 3 * * *'
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        npm ci
        npx playwright install
        
    - name: Start API server
      run: |
        cd apps/api
        npm ci
        npm run dev &
        sleep 15
        
    - name: Run smoke tests
      run: |
        npx playwright test tests/smoke/flight-api.spec.ts --reporter=github
        npx playwright test tests/smoke/flight-fallback.spec.ts --reporter=github
        npx playwright test tests/smoke/slo.spec.ts --reporter=github
      env:
        API_BASE_URL: http://localhost:4000
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: smoke-test-results
        path: test-results/
        
    - name: Stop API server
      if: always()
      run: |
        pkill -f "node" || true